{% set name = "cudasirecon" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scopetools/cudasirecon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b2db4ed214c7b9cb1b36801fea3942e65b9a5c1b45cdd04c47b5585790fee340

build:
  number: 2
  skip: True  # [osx or (cuda_compiler_version in ('None', 'undefined'))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [linux]
    - ninja  # [win]
  host:
    - boost-cpp
    - libgomp  # [linux]
    - libblas
    - liblapack
    - libtiff
    - fftw
  run:
    - boost-cpp

test:
  requires:
    - python=3.9
  commands:
    - cudasirecon --help
    - python -c "import ctypes.util; assert ctypes.CDLL(ctypes.util.find_library('cudasirecon'))._name"
    # - makeotf -h  # doesn't work because of wrong exit code

about:
  home: https://github.com/scopetools/cudasirecon
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 3-beam SIM reconstruction software, with CUDA acceleration
  doc_url: https://github.com/scopetools/cudasirecon#readme
  dev_url: https://github.com/scopetools/cudasirecon

extra:
  recipe-maintainers:
    - tlambert03
    - linshaova
